export const LangStrings = {
  en: {
    about: 'About',
    home: 'Home Page',
    admin: 'Admin Panel',
    siteName: 'Taverna',
    goBack: 'Go Back',
    categoryName: 'Category Name',
    categoryDescription: 'Category Description',
    categoryUpdated: 'Category updated successfully!',
    categoryCreated: 'Category created successfully!',
    submitting: 'Submitting...',
    submit: 'Submit',
    pressToCreateCategory: 'Press to create new category',
    createCategoryForm: 'Create Category Form',
    categoryDeleted: 'Category deleted successfully!',
    errorDeletingCategory: 'Error deleting category!',
    addNewProduct: 'Add new product',
    editCategory: 'Edit category',
    deleteCategory: 'Delete category',
    deleteAllProductsInCategory: 'Delete all products in category',
    areYouSureYouWantToDeleteThisCategory: 'Are you sure you want to delete this category?',
    areYouSureYouWantToDeleteAllProductsInThisCategory: 'Are you sure you want to delete all products in this category?',
    noProductsInCategory: 'No products in this category',
    productDeleted: 'Product deleted successfully!',
    productUpdated: 'Product updated successfully!',
    productCreated: 'Product created successfully!',
    errorDeletingProduct: 'Error deleting product!',
    editProductDetails: 'Edit product details',
    deleteProduct: 'Delete product',
    areYouSureYouWantToDelete: 'Are you sure you want to delete',
    title: 'Title',
    price: 'Price',
    priceInEUR: 'Price (in EUR)',
    description: 'Description',
    productDescription: 'Product description',
    actions: 'Actions',
    productTitle: 'Product title',
    close: 'Close',
    productNameIsRequired: 'Product name is required',
    priceMustBeGreaterThan0: 'Price must be greater than 0',
    priceMustBeLessThan10000: 'Price must be less than 10000',
  },
  ua: {
    about: 'Про нас',
    home: 'Домашня сторінка',
    admin: 'Адмін панель',
    siteName: 'Taverna',
    goBack: 'Повернутися',
    categoryName: 'Назва категорії',
    categoryDescription: 'Опис категорії',
    categoryUpdated: 'Категорія успішно оновлена!',
    submitting: 'Відправка...',
    submit: 'Відправити',
    pressToCreateCategory: 'Натисніть, щоб створити нову категорію',
    createCategoryForm: 'Форма створення категорії',
    categoryDeleted: 'Категорія успішно видалена!',
    errorDeletingCategory: 'Помилка видалення категорії!',
    addNewProduct: 'Додати новий продукт',
    editCategory: 'Редагувати категорію',
    deleteCategory: 'Видалити категорію',
    deleteAllProductsInCategory: 'Видалити всі продукти в категорії',
    areYouSureYouWantToDeleteThisCategory: 'Ви впевнені, що хочете видалити цю категорію?',
    areYouSureYouWantToDeleteAllProductsInThisCategory: 'Ви впевнені, що хочете видалити всі продукти в цій категорії?',
    noProductsInCategory: 'Немає продуктів в цій категорії',
    productDeleted: 'Продукт успішно видалено!',
    productUpdated: 'Продукт успішно оновлено!',
    productCreated: 'Продукт успішно створено!',
    errorDeletingProduct: 'Помилка видалення продукту!',
    editProductDetails: 'Редагувати деталі продукту',
    deleteProduct: 'Видалити продукт',
    areYouSureYouWantToDelete: 'Ви впевнені, що хочете видалити',
    title: 'Назва',
    price: 'Ціна',
    priceInEUR: 'Ціна (в EUR)',
    description: 'Опис',
    productDescription: 'Опис продукту',
    actions: 'Дії',
    productTitle: 'Назва продукту',
    close: 'Закрити',
    productNameIsRequired: 'Назва продукту обов\'язкова',
    priceMustBeGreaterThan0: 'Ціна повинна бути більше 0',
    priceMustBeLessThan10000: 'Ціна повинна бути менше 10000',
  },
  it: {
    about: 'Informazioni su',
    home: 'Pagina iniziale',
    admin: 'Pannello di amministrazione',
    siteName: 'Taverna',
    goBack: 'Torna indietro',
    categoryName: 'Nome della categoria',
    categoryDescription: 'Descrizione della categoria',
    categoryUpdated: 'Categoria aggiornata con successo!',
    submitting: 'Invio...',
    submit: 'Invia',
    pressToCreateCategory: 'Premi per creare una nuova categoria',
    createCategoryForm: 'Modulo di creazione della categoria',
    categoryDeleted: 'Categoria eliminata con successo!',
    errorDeletingCategory: 'Errore durante l\'eliminazione della categoria!',
    addNewProduct: 'Aggiungi nuovo prodotto',
    editCategory: 'Modifica categoria',
    deleteCategory: 'Elimina categoria',
    deleteAllProductsInCategory: 'Elimina tutti i prodotti nella categoria',
    areYouSureYouWantToDeleteThisCategory: 'Sei sicuro di voler eliminare questa categoria?',
    areYouSureYouWantToDeleteAllProductsInThisCategory: 'Sei sicuro di voler eliminare tutti i prodotti in questa categoria?',
    noProductsInCategory: 'Nessun prodotto in questa categoria',
    productDeleted: 'Prodotto eliminato con successo!',
    productUpdated: 'Prodotto aggiornato con successo!',
    productCreated: 'Prodotto creato con successo!',
    errorDeletingProduct: 'Errore durante l\'eliminazione del prodotto!',
    editProductDetails: 'Modifica dettagli prodotto',
    deleteProduct: 'Elimina prodotto',
    areYouSureYouWantToDelete: 'Sei sicuro di voler eliminare',
    title: 'Titolo',
    price: 'Prezzo',
    priceInEUR: 'Prezzo (in EUR)',
    description: 'Descrizione',
    productDescription: 'Descrizione del prodotto',
    actions: 'Azioni',
    productTitle: 'Titolo del prodotto',
    close: 'Chiudi',
    productNameIsRequired: 'Il nome del prodotto è obbligatorio',
    priceMustBeGreaterThan0: 'Il prezzo deve essere maggiore di 0',
    priceMustBeLessThan10000: 'Il prezzo deve essere inferiore a 10000',
  },
};
